version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/"
    target-branch: "dev"
    schedule:
      interval: "daily"
    groups:
      minor-patch-updates:
        patterns: ["FluentAssertions"]
        update-types: ["minor", "patch"]  