name: gh-pages

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: always() && !failure() && !cancelled()
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x
    - name: Version Increment
      id: version
      uses: reecetech/version-increment@2024.4.4
      with:
        scheme: calver
        increment: patch
    - name: DotNet Bump Version
      id: update
      uses: vers-one/dotnet-project-version-updater@v1.7
      with:
        file: "src/**/*.csproj"
        version: "${{ steps.version.outputs.major-version }}.${{ steps.version.outputs.minor-version }}.${{ steps.version.outputs.patch-version }}.0" 
    - name: .NET WASM Workload
      run: dotnet workload install wasm-tools
    - name: Publish with dotnet
      run: dotnet publish ./src/MegaSchool1 --configuration Release --output build
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: main # The branch the action should deploy from.
        BRANCH: gh-pages-from-actions # The branch the action should deploy to.
        FOLDER: build/wwwroot # The folder the action should deploy.      
        SINGLE_COMMIT: true

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: always() && !failure() && !cancelled()
    steps:
    - name: Version Increment
      id: version
      uses: reecetech/version-increment@2024.4.4
      with:
        scheme: calver
        use_api: true
    - uses: "marvinpinto/action-automatic-releases@v1.2.1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "v${{ steps.version.outputs.major-version }}.${{ steps.version.outputs.minor-version }}.${{ steps.version.outputs.patch-version }}"
